---
title: Dimension Reduction in MNIST
author: Zhenhua Wang, Zewei Kong
output: pdf_document
---

```{r}
## require(devtools)
## install_version("lle", version = "1.1", repos = "http://cran.us.r-project.org")
library(tidyverse)
library(RDRToolbox)
library(Matrix)
library(xgboost)
```

```{r}
mnist_data <- read.csv("./mnist/train.csv")
## load lower dimension representation
low_dim_rep <- read.csv("./output/mnist_autoencoder.csv")
x <- data %>% select(-label)
y <- data$label

train_idx <- sample(seq_len(nrow(x)), round(nrow(x) * 0.85))
val_idx  <- (seq_len(nrow(x)))[-train_idx]
train_x <- as.matrix(x[train_idx, ])
train_y <- y[train_idx]
val_x <- as.matrix(x[val_idx, ])
val_y <- y[val_idx]

mnist_model <-
  xgboost(
    data = train_x,
    label = train_y,
    nrounds = 1000,
    objective = "multi:softmax",
    num_class = 10,
    early_stopping_rounds = 5,
    max_depth = 2,
    eta = .8)
y_hat <- predict(mnist_model, val_x)
mean(val_y == y_hat)
```

```{r}
train_data <- read.csv("./mnist/train.csv")
test_data <- read.csv("./mnist/test.csv")
## load lower dimension representation
train_x_low_data <- read.csv("./output/mnist_autoencoder.csv")
test_x_low_data <- read.csv("")
train_x <- as.matrix(train_x_low_data)
train_y <- train_data$label
test_x <- as.matrix(test_x_low_data)

mnist_model <-
  xgboost(
    data = train_x,
    label = train_y,
    nrounds = 10,
    objective = "multi:softmax",
    num_class = 10,
    early_stopping_rounds = 5,
    max_depth = 2,
    eta = .8)
y_hat <- predict(mnist_model, test_x)
submission <- data.frame(ImageId = seq_len(nrow(test_x)), Label = y_hat)
write.csv(submission, "./submission.csv")
```
